name = "Folkwang"
author = "Mr_Poeschl"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "045cf79b066aae34e7c1f1447f331f0adf560d7d9257214eaceb4077601fff8e"

[versions]
forge = "36.2.35"
minecraft = "1.16.5"

[options]
no-internal-hashes = true
