name = "Folkwang"
author = "Mr_Poeschl"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "653b3767e29f9e9bb5efea5f4da514b23b7ab528c806a188c9e4c048445721d5"

[versions]
forge = "36.2.35"
minecraft = "1.16.5"

[options]
no-internal-hashes = true
