name = "Folkwang"
author = "Mr_Poeschl"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "becefd111f3a7dd179913f32afad169842f05ab06e85ba035b6a2084a53a4007"

[versions]
forge = "36.2.35"
minecraft = "1.16.5"

[options]
no-internal-hashes = true
